add some files
CREATE-ROCKET/Avi_ESP_Libs pull request #14
Opened 2023-08-18 04:35 UTC by IamMichaelthankyou

## 変更概要

例となるコードを追加、センサーの説明を追加

## 後方互換性

- [ ] 既存コードとの後方互換性を保っている

## 動作確認

- [x] 実際にセンサを接続して動作確認を行った

## 種別

- [ ] 新規センサのライブラリ

- [x] 既存センサのライブラリ
    - [ ] 新機能の追加
    - [ ] バグ修正
    - [x] その他

## 変更点の詳細
examples/main.cppとdocs/information.txtを追加しました。

2023-08-18 04:57 UTC, Luftalian commented
https://github.com/CREATE-ROCKET/Avi_ESP_Libs/blob/cpp_lint/.vscode/settings.json

これ参考にformatter設定してもらうと簡単にできるはず

2023-08-18 05:02 UTC, IamMichaelthankyou commented
> https://github.com/CREATE-ROCKET/Avi_ESP_Libs/blob/cpp_lint/.vscode/settings.json
> 
> これ参考にformatter設定してもらうと簡単にできるはず

ありがとうございます。

2023-08-18 22:16 UTC, Luftalian requested changes
```
    uint32_t PlessureRaw;
    int Plessure;
    void begin(SPICREATE::SPICreate *targetSPI, int cs,
               uint32_t freq = 8000000);
    uint8_t WhoAmI();
    void Get(uint8_t *rx);
```
全体的には良さそうです
以下の点を改善してください
- ライブラリに実装されている全ての関数を使うようにしてください。今回の場合上のやつ。
- 各関数が何をやっているのか簡単にコメントアウトで書く

2023-08-28 11:44 UTC, Luftalian commented on .vscode/extensions.json
これは消さないで

2023-08-28 11:44 UTC, Luftalian commented on .vscode/settings.json
これは消さないで

2023-08-28 11:45 UTC, Luftalian requested changes
.vscodeのファイルは消さないでほしいです

2023-08-28 11:47 UTC, Luftalian approved these changes

2023-08-28 11:47 UTC, Luftalian commented on LPS25HB 1.0.0/examples/main.cpp
> +    lps.begin(&spi, CS, 5000000);  // LPSのCSピン、SPI通信の設定
できれば5000000は外で変数として定義してほしいです

2023-09-05 15:55 UTC, Luftalian requested changes

2023-09-05 15:55 UTC, Luftalian commented on LPS25HB 1.0.0/.vscode/extensions.json
ファイルを置くディレクトリが変わってしまったようです。

2023-09-05 15:55 UTC, Luftalian commented on LPS25HB 1.0.0/.vscode/settings.json
これも変わってしまったみたいです

2023-09-13 12:44 UTC, Luftalian approved these changes

2023-09-13 12:45 UTC, Luftalian commented
よさそうです！

2023-09-14 03:31 UTC, Luftalian reviewed
できたらinformation.txtにdatasheetのリンクを貼り付けてほしいです。

2023-09-20 10:10 UTC, Luftalian approved these changes
良さそうです！mergeしちゃってください

2023-09-20 10:11 UTC, merged